angular.module('route',[])
    .config(function($stateProvider,$urlRouterProvider){
        $stateProvider
            .state('/',{
                url:'/',
                templateUrl:'templates/index.html',
                controller:'IndexController'
            })
            .state('list', {
                url:'/list/:id',
                templateUrl:'templates/list.html',
                controller:'ListController'
            })
            .state('detail',{
                url:'/detail/:id',
                templateUrl:'templates/detail.html',
                controller:'DetailController'
            })
            .state('search',{
                url:'/search',
                templateUrl:'templates/search.html',
                controller:'SearchController'
            })
            .state('my',{
                url:'/my',
                templateUrl:'templates/my.html',
                controller:'MyController'
            })

        $urlRouterProvider.otherwise('/');
    })